server:
  port: 8083  #设置端口号
  servlet:
    context-path: /svedio


spring:
  datasource:
    url: jdbc:mysql://123.56.232.18:3306/serverdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/serverdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ppjoke2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      init-s-q-l: SET NAMES utf8mb4

    servlet:
      multipart:
        file-size-threshold:2KB
        max-file-size:200MB
        max-request-size:215MB

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.macro.mall.vedio.table
  mapper-locations: classpath:/mapper/*.xml
